'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class ArticulosCantidades
        Public Property IdArticuloCantidad As Integer
        Public Property IdArticulo As Integer
        Public Property IdDeposito As Integer
        Public Property Fecha As Date
        Public Property Descripcion As String
        Public Property Cantidad As Integer
        Public Property IdComprobanteEmitidoDetalle As Nullable(Of Integer)
        Public Property IdComprobanteRecibidoDetalle As Nullable(Of Integer)
        Public Property IdComprobanteRemitoEmitidoDetalle As Nullable(Of Integer)
        Public Property IdComprobanteRemitoRecibidoDetalle As Nullable(Of Integer)
    
        Public Overridable Property Articulos As Articulos
        Public Overridable Property ComprobantesEmitidosDetalle As ComprobantesEmitidosDetalle
        Public Overridable Property ComprobantesRecibidosDetalle As ComprobantesRecibidosDetalle
        Public Overridable Property ComprobantesRemitosEmitidosDetalle As ComprobantesRemitosEmitidosDetalle
        Public Overridable Property ComprobantesRemitosRecibidosDetalle As ComprobantesRemitosRecibidosDetalle
        Public Overridable Property Depositos As Depositos
    
    End Class

End Namespace
