'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class ArticulosPreciosCosto
        Public Property IdArticuloPrecioCosto As Integer
        Public Property IdArticulo As Integer
        Public Property Fecha As Date
        Public Property Descripcion As String
        Public Property Cantidad As Integer
        Public Property PrecioCostoNeto As Decimal
        Public Property PrecioCostoBruto As Decimal
        Public Property Activo As Boolean
    
        Public Overridable Property Articulos As Articulos
    
    End Class

End Namespace
