'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class ArticulosImagenes
        Public Property IdArticuloImagen As Integer
        Public Property IdArticulo As Integer
        Public Property Imagen1 As String
        Public Property Imagen2 As String
        Public Property Imagen3 As String
        Public Property Imagen4 As String
        Public Property Imagen5 As String
        Public Property Imagen6 As String
        Public Property FechaAlta As Date
        Public Property FechaModificacion As Date
    
        Public Overridable Property Articulos As Articulos
    
    End Class

End Namespace
