'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class ArticulosOnlineDetalle
        Public Property IdArticuloOnlineDetalle As Integer
        Public Property IdArticuloOnline As Integer
        Public Property IdArticulo As Integer
        Public Property CodigoArticulo As String
        Public Property IdEscala1 As Integer
        Public Property IdEscala2 As Integer
        Public Property Stock As Integer
    
        Public Overridable Property ArticulosOnline As ArticulosOnline
        Public Overridable Property Escalas1 As Escalas1
        Public Overridable Property Escalas2 As Escalas2
    
    End Class

End Namespace
