'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class Articulos
        Public Property IdArticulo As Integer
        Public Property Articulo As String
        Public Property Incremento As Nullable(Of Integer)
        Public Property CodigoArticulo As String
        Public Property CodigoBarra As String
        Public Property CodigoFabricante As String
        Public Property Descripcion As String
        Public Property DescripcionDetallada As String
        Public Property IdProveedor As Integer
        Public Property IdEscala1 As Integer
        Public Property IdEscala2 As Integer
        Public Property IdSubRubro As Integer
        Public Property IdArticuloPerfil As Integer
        Public Property IdTasaIVAVentas As Integer
        Public Property IdTasaIVACompras As Integer
        Public Property PermiteDevolucion As Boolean
        Public Property PermiteDescuento As Boolean
        Public Property ActivoOnline As Boolean
        Public Property PublicarOnline As Boolean
        Public Property EstadoOnline As String
        Public Property PermiteMoverStock As Boolean
        Public Property FechaAlta As Date
        Public Property FechaModificacion As Date
        Public Property StockPuntoReposicion As Integer
        Public Property StockPuntoCritico As Integer
        Public Property Utilidad As Decimal
        Public Property CantidadBultos As Decimal
        Public Property Activo As Boolean
    
        Public Overridable Property ArticulosPerfiles As ArticulosPerfiles
        Public Overridable Property Escalas1 As Escalas1
        Public Overridable Property Escalas2 As Escalas2
        Public Overridable Property Proveedores As Proveedores
        Public Overridable Property SubRubros As SubRubros
        Public Overridable Property TasasIVACompras As TasasIVACompras
        Public Overridable Property TasasIVAVentas As TasasIVAVentas
        Public Overridable Property ArticulosCantidades As ICollection(Of ArticulosCantidades) = New HashSet(Of ArticulosCantidades)
        Public Overridable Property ArticulosPreciosCosto As ICollection(Of ArticulosPreciosCosto) = New HashSet(Of ArticulosPreciosCosto)
        Public Overridable Property ArticulosImagenes As ICollection(Of ArticulosImagenes) = New HashSet(Of ArticulosImagenes)
        Public Overridable Property ArticulosPreciosVenta As ICollection(Of ArticulosPreciosVenta) = New HashSet(Of ArticulosPreciosVenta)
        Public Overridable Property ComprobantesEmitidosDetalle As ICollection(Of ComprobantesEmitidosDetalle) = New HashSet(Of ComprobantesEmitidosDetalle)
        Public Overridable Property ComprobantesPedidosRecibidosDetalle As ICollection(Of ComprobantesPedidosRecibidosDetalle) = New HashSet(Of ComprobantesPedidosRecibidosDetalle)
        Public Overridable Property ComprobantesPresupuestosEmitidosDetalle As ICollection(Of ComprobantesPresupuestosEmitidosDetalle) = New HashSet(Of ComprobantesPresupuestosEmitidosDetalle)
        Public Overridable Property ComprobantesRecibidosDetalle As ICollection(Of ComprobantesRecibidosDetalle) = New HashSet(Of ComprobantesRecibidosDetalle)
        Public Overridable Property ComprobantesRemitosEmitidosDetalle As ICollection(Of ComprobantesRemitosEmitidosDetalle) = New HashSet(Of ComprobantesRemitosEmitidosDetalle)
        Public Overridable Property ComprobantesRemitosRecibidosDetalle As ICollection(Of ComprobantesRemitosRecibidosDetalle) = New HashSet(Of ComprobantesRemitosRecibidosDetalle)
    
    End Class

End Namespace
