'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class ArticulosPerfiles
        Public Property IdArticuloPerfil As Integer
        Public Property ArticuloPerfil As String
        Public Property Descripcion As String
        Public Property CodificacionAutomatica As Nullable(Of Boolean)
        Public Property LongitudRubro As Integer
        Public Property LongitudSubRubro As Integer
        Public Property LongitudCodigo As Integer
        Public Property Activo As Boolean
    
        Public Overridable Property Articulos As ICollection(Of Articulos) = New HashSet(Of Articulos)
    
    End Class

End Namespace
