'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class ArticulosPreciosVenta
        Public Property IdArticuloPrecioVenta As Integer
        Public Property IdArticulo As Integer
        Public Property Fecha As Date
        Public Property Descripcion As String
        Public Property PrecioTiendaOnline As Decimal
        Public Property PrecioVenta1Neto As Decimal
        Public Property PrecioVenta1Bruto As Decimal
        Public Property PrecioVenta2Neto As Decimal
        Public Property PrecioVenta2Bruto As Decimal
        Public Property PrecioVenta3Neto As Decimal
        Public Property PrecioVenta3Bruto As Decimal
        Public Property PrecioVenta4Neto As Decimal
        Public Property PrecioVenta4Bruto As Decimal
        Public Property PrecioVenta5Neto As Decimal
        Public Property PrecioVenta5Bruto As Decimal
        Public Property Activo As Boolean
    
        Public Overridable Property Articulos As Articulos
    
    End Class

End Namespace
