'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class ArticulosOnline
        Public Property IdArticuloOnline As Integer
        Public Property Articulo As String
        Public Property Descripcion As String
        Public Property DescripcionDetallada As String
        Public Property IdSubRubro As Integer
        Public Property FechaSincronizacion As Date
        Public Property PrecioTienda As Decimal
        Public Property PrecioTiendaOnline As Decimal
        Public Property Imagen1 As String
        Public Property Imagen2 As String
        Public Property Imagen3 As String
        Public Property Imagen4 As String
        Public Property Imagen5 As String
        Public Property Imagen6 As String
        Public Property EstadoOnline As String
        Public Property Activo As Boolean
    
        Public Overridable Property SubRubros As SubRubros
        Public Overridable Property ArticulosOnlineDetalle As ICollection(Of ArticulosOnlineDetalle) = New HashSet(Of ArticulosOnlineDetalle)
    
    End Class

End Namespace
