'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class CajaMovimientos
        Public Property IdMovimiento As Integer
        Public Property IdUsuario As Integer
        Public Property IdTipoMovimiento As Integer
        Public Property IdComprobanteCobroDetalle As Nullable(Of Integer)
        Public Property IdComprobantePagoDetalle As Nullable(Of Integer)
        Public Property Fecha As Date
        Public Property Descripcion As String
        Public Property Debe As Decimal
        Public Property Haber As Decimal
        Public Property TipoCaja As String
        Public Property PuntoVenta As Decimal
        Public Property Activo As Boolean
    
        Public Overridable Property ComprobantesCobrosDetalle As ComprobantesCobrosDetalle
        Public Overridable Property ComprobantesPagosDetalle As ComprobantesPagosDetalle
        Public Overridable Property TiposMovimientos As TiposMovimientos
        Public Overridable Property Usuarios As Usuarios
    
    End Class

End Namespace
