'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class CajaCierres
        Public Property IdCajaCierre As Integer
        Public Property FechaInicio As Date
        Public Property FechaCierre As Date
        Public Property Estado As String
        Public Property PuntoVenta As Decimal
    
    End Class

End Namespace
