'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class ClientesCtasCtes
        Public Property IdCtaCteMovimiento As Integer
        Public Property IdCtaCte As Integer
        Public Property Fecha As Date
        Public Property Debe As Decimal
        Public Property Haber As Decimal
        Public Property Activo As Boolean
    
        Public Overridable Property ClientesNumerosCtasCtes As ClientesNumerosCtasCtes
        Public Overridable Property ComprobantesCobros As ICollection(Of ComprobantesCobros) = New HashSet(Of ComprobantesCobros)
        Public Overridable Property ComprobantesEmitidos As ICollection(Of ComprobantesEmitidos) = New HashSet(Of ComprobantesEmitidos)
    
    End Class

End Namespace
