'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class ClientesNumerosCtasCtes
        Public Property IdCtaCte As Integer
        Public Property IdCliente As Integer
        Public Property Descripcion As String
        Public Property FechaAlta As Date
        Public Property FechaBaja As Date
        Public Property Activo As Boolean
    
        Public Overridable Property Clientes As Clientes
        Public Overridable Property ClientesCtasCtes As ICollection(Of ClientesCtasCtes) = New HashSet(Of ClientesCtasCtes)
    
    End Class

End Namespace
