'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class ComprobantesCobrosDetalle
        Public Property IdComprobanteDetalle As Integer
        Public Property IdComprobante As Integer
        Public Property IdFormaPago As Integer
        Public Property Descripcion As String
        Public Property Monto As Decimal
    
        Public Overridable Property CajaMovimientos As ICollection(Of CajaMovimientos) = New HashSet(Of CajaMovimientos)
        Public Overridable Property ComprobantesCobros As ComprobantesCobros
        Public Overridable Property DetalleChequesRecibidos As ICollection(Of DetalleChequesRecibidos) = New HashSet(Of DetalleChequesRecibidos)
        Public Overridable Property FormasPago As FormasPago
        Public Overridable Property DetalleCobrosBancos As ICollection(Of DetalleCobrosBancos) = New HashSet(Of DetalleCobrosBancos)
        Public Overridable Property DetalleCobrosTarjetas As ICollection(Of DetalleCobrosTarjetas) = New HashSet(Of DetalleCobrosTarjetas)
    
    End Class

End Namespace
