'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class ComprobantesPagosDetalle
        Public Property IdComprobanteDetalle As Integer
        Public Property IdComprobante As Integer
        Public Property IdFormaPago As Integer
        Public Property Descripcion As String
        Public Property Monto As Decimal
    
        Public Overridable Property CajaMovimientos As ICollection(Of CajaMovimientos) = New HashSet(Of CajaMovimientos)
        Public Overridable Property ComprobantesPagos As ComprobantesPagos
        Public Overridable Property FormasPago As FormasPago
        Public Overridable Property DetalleChequesEmitidos As ICollection(Of DetalleChequesEmitidos) = New HashSet(Of DetalleChequesEmitidos)
        Public Overridable Property DetallePagosBancos As ICollection(Of DetallePagosBancos) = New HashSet(Of DetallePagosBancos)
    
    End Class

End Namespace
