'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class ComprobantesRecibidos
        Public Property IdComprobante As Integer
        Public Property IdCtaCteMovimiento As Integer
        Public Property IdUsuario As Integer
        Public Property Fecha As Date
        Public Property FechaVencimiento As Date
        Public Property Comprobante As String
        Public Property TipoComprobante As String
        Public Property PuntoVenta As Decimal
        Public Property NumeroComprobante As Decimal
        Public Property MontoNeto As Decimal
        Public Property MontoBruto As Decimal
        Public Property Saldo As Decimal
        Public Property TasaIva1 As Decimal
        Public Property MontoIva1 As Decimal
        Public Property TasaIva2 As Decimal
        Public Property MontoIva2 As Decimal
        Public Property MontoImpInt As Decimal
        Public Property MontoPIva As Decimal
        Public Property MontoPIIBB As Decimal
        Public Property Observacion As String
        Public Property Activo As Boolean
    
        Public Overridable Property ProveedoresCtasCtes As ProveedoresCtasCtes
        Public Overridable Property Usuarios As Usuarios
        Public Overridable Property ComprobantesRecibidosDetalle As ICollection(Of ComprobantesRecibidosDetalle) = New HashSet(Of ComprobantesRecibidosDetalle)
        Public Overridable Property ComprobantesRecibidosVencimientos As ICollection(Of ComprobantesRecibidosVencimientos) = New HashSet(Of ComprobantesRecibidosVencimientos)
    
    End Class

End Namespace
