'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class ComprobantesRemitosRecibidos
        Public Property IdComprobante As Integer
        Public Property IdProveedor As Integer
        Public Property IdUsuario As Integer
        Public Property IdVendedor As Integer
        Public Property IdTransporte As Integer
        Public Property Fecha As Date
        Public Property Comprobante As String
        Public Property TipoComprobante As String
        Public Property PuntoVenta As Decimal
        Public Property NumeroComprobante As Decimal
        Public Property Monto As Decimal
        Public Property Observacion As String
        Public Property CantidadBultos As Decimal
        Public Property Activo As Boolean
    
        Public Overridable Property Proveedores As Proveedores
        Public Overridable Property Transportes As Transportes
        Public Overridable Property Usuarios As Usuarios
        Public Overridable Property Vendedores As Vendedores
        Public Overridable Property ComprobantesRemitosRecibidosDetalle As ICollection(Of ComprobantesRemitosRecibidosDetalle) = New HashSet(Of ComprobantesRemitosRecibidosDetalle)
    
    End Class

End Namespace
