'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class ComprobantesRecibidosVencimientos
        Public Property IdComprobanteVencimiento As Integer
        Public Property IdComprobante As Integer
        Public Property FechaVencimientoCuota As Date
        Public Property Cuota As Integer
        Public Property Cuotas As Integer
        Public Property MontoCuota As Decimal
        Public Property Saldo As Decimal
    
        Public Overridable Property ComprobantesRecibidos As ComprobantesRecibidos
    
    End Class

End Namespace
