'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class CondicionesPago
        Public Property IdCondicionPago As Integer
        Public Property CondicionPago As String
        Public Property Descripcion As String
        Public Property FechaVencimientoDias As Integer
        Public Property DiasEntreCuotas As Integer
        Public Property DiasTotales As Integer
        Public Property Cuotas As Integer
        Public Property Cuota1Dias As Integer
        Public Property Cuota1Porcentaje As Decimal
        Public Property Cuota2Dias As Integer
        Public Property Cuota2Porcentaje As Decimal
        Public Property Cuota3Dias As Integer
        Public Property Cuota3Porcentaje As Decimal
        Public Property Cuota4Dias As Integer
        Public Property Cuota4Porcentaje As Decimal
        Public Property Cuota5Dias As Integer
        Public Property Cuota5Porcentaje As Decimal
        Public Property Cuota6Dias As Integer
        Public Property Cuota6Porcentaje As Decimal
        Public Property Cuota7Dias As Integer
        Public Property Cuota7Porcentaje As Decimal
        Public Property Cuota8Dias As Integer
        Public Property Cuota8Porcentaje As Decimal
        Public Property Cuota9Dias As Integer
        Public Property Cuota9Porcentaje As Decimal
        Public Property Cuota10Dias As Integer
        Public Property Cuota10Porcentaje As Decimal
        Public Property Activo As Boolean
    
        Public Overridable Property Clientes As ICollection(Of Clientes) = New HashSet(Of Clientes)
        Public Overridable Property Proveedores As ICollection(Of Proveedores) = New HashSet(Of Proveedores)
    
    End Class

End Namespace
