'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class CondicionesIva
        Public Property IdCondicionIva As Integer
        Public Property CondicionIva As String
        Public Property Activo As Boolean
    
        Public Overridable Property Clientes As ICollection(Of Clientes) = New HashSet(Of Clientes)
        Public Overridable Property Empresa As ICollection(Of Empresa) = New HashSet(Of Empresa)
        Public Overridable Property Proveedores As ICollection(Of Proveedores) = New HashSet(Of Proveedores)
        Public Overridable Property TiposComprobantes As ICollection(Of TiposComprobantes) = New HashSet(Of TiposComprobantes)
        Public Overridable Property TiposComprobantes1 As ICollection(Of TiposComprobantes) = New HashSet(Of TiposComprobantes)
        Public Overridable Property Transportes As ICollection(Of Transportes) = New HashSet(Of Transportes)
    
    End Class

End Namespace
