'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class ConfiguracionPresupuesto
        Public Property IdConfiguracionPresupuesto As Integer
        Public Property Papel As String
        Public Property Fuente As String
        Public Property FuenteTamaño As Integer
        Public Property MargenLeft As Integer
        Public Property MargenRight As Integer
        Public Property MargenTop As Integer
        Public Property MargenBottom As Integer
        Public Property FechaImpresionTOP As Integer
        Public Property FechaImpresionLEFT As Integer
        Public Property FechaImpresionWIDTH As Integer
        Public Property IdComprobanteTOP As Integer
        Public Property IdComprobanteLEFT As Integer
        Public Property IdComprobanteWIDTH As Integer
        Public Property ComprobanteTOP As Integer
        Public Property ComprobanteLEFT As Integer
        Public Property ComprobanteWIDTH As Integer
        Public Property TipoComprobanteTOP As Integer
        Public Property TipoComprobanteLEFT As Integer
        Public Property TipoComprobanteWIDTH As Integer
        Public Property NumeroComprobanteTOP As Integer
        Public Property NumeroComprobanteLEFT As Integer
        Public Property NumeroComprobanteWIDTH As Integer
        Public Property FechaEmisionTOP As Integer
        Public Property FechaEmisionLEFT As Integer
        Public Property FechaEmisionWIDTH As Integer
        Public Property IdClienteTOP As Integer
        Public Property IdClienteLEFT As Integer
        Public Property IdClienteWIDTH As Integer
        Public Property ClienteTOP As Integer
        Public Property ClienteLEFT As Integer
        Public Property ClienteWIDTH As Integer
        Public Property DomicilioTOP As Integer
        Public Property DomicilioLEFT As Integer
        Public Property DomicilioWIDTH As Integer
        Public Property ProvinciaTOP As Integer
        Public Property ProvinciaLEFT As Integer
        Public Property ProvinciaWIDTH As Integer
        Public Property LocalidadTOP As Integer
        Public Property LocalidadLEFT As Integer
        Public Property LocalidadWIDTH As Integer
        Public Property CuitTOP As Integer
        Public Property CuitLEFT As Integer
        Public Property CuitWIDTH As Integer
        Public Property CondicionIvaTOP As Integer
        Public Property CondicionIvaLEFT As Integer
        Public Property CondicionIvaWIDTH As Integer
        Public Property CodigoArticuloTOP As Integer
        Public Property CodigoArticuloLEFT As Integer
        Public Property CodigoArticuloWIDTH As Integer
        Public Property DescripcionTOP As Integer
        Public Property DescripcionLEFT As Integer
        Public Property DescripcionWIDTH As Integer
        Public Property CantidadTOP As Integer
        Public Property CantidadLEFT As Integer
        Public Property CantidadWIDTH As Integer
        Public Property VendedorTOP As Integer
        Public Property VendedorLEFT As Integer
        Public Property VendedorWIDTH As Integer
        Public Property ObservacionTOP As Integer
        Public Property ObservacionLEFT As Integer
        Public Property ObservacionWIDTH As Integer
    
    End Class

End Namespace
