'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class ConfiguracionOrdenPago
        Public Property IdConfiguracionOrdenPago As Integer
        Public Property Papel As String
        Public Property Fuente As String
        Public Property FuenteTamaño As Integer
        Public Property MargenLeft As Integer
        Public Property MargenRight As Integer
        Public Property MargenTop As Integer
        Public Property MargenBottom As Integer
        Public Property FechaImpresionTOP As Integer
        Public Property FechaImpresionLEFT As Integer
        Public Property FechaImpresionWIDTH As Integer
        Public Property IdComprobanteTOP As Integer
        Public Property IdComprobanteLEFT As Integer
        Public Property IdComprobanteWIDTH As Integer
        Public Property ComprobanteTOP As Integer
        Public Property ComprobanteLEFT As Integer
        Public Property ComprobanteWIDTH As Integer
        Public Property TipoComprobanteTOP As Integer
        Public Property TipoComprobanteLEFT As Integer
        Public Property TipoComprobanteWIDTH As Integer
        Public Property NumeroComprobanteTOP As Integer
        Public Property NumeroComprobanteLEFT As Integer
        Public Property NumeroComprobanteWIDTH As Integer
        Public Property FechaEmisionTOP As Integer
        Public Property FechaEmisionLEFT As Integer
        Public Property FechaEmisionWIDTH As Integer
        Public Property IdProveedorTOP As Integer
        Public Property IdProveedorLEFT As Integer
        Public Property IdProveedorWIDTH As Integer
        Public Property ProveedorTOP As Integer
        Public Property ProveedorLEFT As Integer
        Public Property ProveedorWIDTH As Integer
        Public Property DomicilioTOP As Integer
        Public Property DomicilioLEFT As Integer
        Public Property DomicilioWIDTH As Integer
        Public Property ProvinciaTOP As Integer
        Public Property ProvinciaLEFT As Integer
        Public Property ProvinciaWIDTH As Integer
        Public Property LocalidadTOP As Integer
        Public Property LocalidadLEFT As Integer
        Public Property LocalidadWIDTH As Integer
        Public Property CuitTOP As Integer
        Public Property CuitLEFT As Integer
        Public Property CuitWIDTH As Integer
        Public Property CondicionIvaTOP As Integer
        Public Property CondicionIvaLEFT As Integer
        Public Property CondicionIvaWIDTH As Integer
        Public Property FormaPagoTOP As Integer
        Public Property FormaPagoLEFT As Integer
        Public Property FormaPagoWIDTH As Integer
        Public Property DescripcionTOP As Integer
        Public Property DescripcionLEFT As Integer
        Public Property DescripcionWIDTH As Integer
        Public Property MontoPagoTOP As Integer
        Public Property MontoPagoLEFT As Integer
        Public Property MontoPagoWIDTH As Integer
        Public Property MontoTotalTOP As Integer
        Public Property MontoTotalLEFT As Integer
        Public Property MontoTotalWIDTH As Integer
        Public Property MontoTotalLetrasTOP As Integer
        Public Property MontoTotalLetrasLEFT As Integer
        Public Property MontoTotalLetrasWIDTH As Integer
        Public Property ObservacionTOP As Integer
        Public Property ObservacionLEFT As Integer
        Public Property ObservacionWIDTH As Integer
    
    End Class

End Namespace
