'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class ControladoresFiscales
        Public Property IdControladorFiscal As Integer
        Public Property Marca As String
        Public Property Modelo As String
        Public Property ModeloNumero As Integer
        Public Property Activo As Boolean
    
        Public Overridable Property ControladoresFiscalesComprobantes As ICollection(Of ControladoresFiscalesComprobantes) = New HashSet(Of ControladoresFiscalesComprobantes)
        Public Overridable Property Talonarios As ICollection(Of Talonarios) = New HashSet(Of Talonarios)
    
    End Class

End Namespace
