'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class ControladoresFiscalesComprobantes
        Public Property IdControladorFiscalComprobante As Integer
        Public Property IdControladorFiscal As Integer
        Public Property Comprobante As String
        Public Property Activo As Boolean
    
        Public Overridable Property ControladoresFiscales As ControladoresFiscales
    
    End Class

End Namespace
