'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class Depositos
        Public Property IdDeposito As Integer
        Public Property Deposito As String
        Public Property Ubicacion As String
        Public Property Activo As Boolean
    
        Public Overridable Property ArticulosCantidades As ICollection(Of ArticulosCantidades) = New HashSet(Of ArticulosCantidades)
    
    End Class

End Namespace
