'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class DetalleCobrosTarjetas
        Public Property IdDetalleCobroTarjeta As Integer
        Public Property IdComprobanteDetalle As Integer
        Public Property IdBanco As Integer
        Public Property Fecha As Date
        Public Property Monto As Decimal
        Public Property Titular As String
        Public Property Documento As Nullable(Of Decimal)
        Public Property Lote As String
        Public Property Cupon As String
        Public Property Autorizacion As String
        Public Property Terminal As String
        Public Property Estado As String
        Public Property Activo As Boolean
    
        Public Overridable Property ComprobantesCobrosDetalle As ComprobantesCobrosDetalle
    
    End Class

End Namespace
