'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class Empresa
        Public Property IdEmpresa As Integer
        Public Property IdCondicionIva As Integer
        Public Property Empresa1 As String
        Public Property Domicilio As String
        Public Property RazonSocial As String
        Public Property Cuit As String
        Public Property IIBB As String
        Public Property Telefonos As String
        Public Property Fax As String
        Public Property Email As String
        Public Property Web As String
        Public Property Observaciones As String
        Public Property Activo As Boolean
    
        Public Overridable Property CondicionesIva As CondicionesIva
    
    End Class

End Namespace
