'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class Escalas2
        Public Property IdEscala2 As Integer
        Public Property Escala2 As String
        Public Property Separador As String
        Public Property Abreviatura As String
        Public Property Activo As Boolean
    
        Public Overridable Property Articulos As ICollection(Of Articulos) = New HashSet(Of Articulos)
        Public Overridable Property ArticulosOnlineDetalle As ICollection(Of ArticulosOnlineDetalle) = New HashSet(Of ArticulosOnlineDetalle)
    
    End Class

End Namespace
