'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class FormasPago
        Public Property IdFormaPago As Integer
        Public Property FormaPago As String
        Public Property Cuotas As Integer
        Public Property Descuento As Decimal
        Public Property Recargo As Decimal
        Public Property Cuenta As String
        Public Property Detalle As String
        Public Property TeclaRapida1 As Integer
        Public Property TeclaRapida2 As Integer
        Public Property Activo As Boolean
    
        Public Overridable Property ComprobantesCobrosDetalle As ICollection(Of ComprobantesCobrosDetalle) = New HashSet(Of ComprobantesCobrosDetalle)
        Public Overridable Property ComprobantesPagosDetalle As ICollection(Of ComprobantesPagosDetalle) = New HashSet(Of ComprobantesPagosDetalle)
    
    End Class

End Namespace
