'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class Localidades
        Public Property IdLocalidad As Integer
        Public Property IdProvincia As Integer
        Public Property Localidad As String
        Public Property Activo As Boolean
    
        Public Overridable Property Clientes As ICollection(Of Clientes) = New HashSet(Of Clientes)
        Public Overridable Property Provincias As Provincias
        Public Overridable Property Proveedores As ICollection(Of Proveedores) = New HashSet(Of Proveedores)
        Public Overridable Property Transportes As ICollection(Of Transportes) = New HashSet(Of Transportes)
        Public Overridable Property Vendedores As ICollection(Of Vendedores) = New HashSet(Of Vendedores)
    
    End Class

End Namespace
