'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class ProveedoresCtasCtes
        Public Property IdCtaCteMovimiento As Integer
        Public Property IdCtaCte As Integer
        Public Property Fecha As Date
        Public Property Debe As Decimal
        Public Property Haber As Decimal
        Public Property Activo As Boolean
    
        Public Overridable Property ComprobantesPagos As ICollection(Of ComprobantesPagos) = New HashSet(Of ComprobantesPagos)
        Public Overridable Property ComprobantesRecibidos As ICollection(Of ComprobantesRecibidos) = New HashSet(Of ComprobantesRecibidos)
        Public Overridable Property ProveedoresNumerosCtasCtes As ProveedoresNumerosCtasCtes
    
    End Class

End Namespace
