'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class Provincias
        Public Property IdProvincia As Integer
        Public Property Provincia As String
        Public Property Activo As Boolean
    
        Public Overridable Property Localidades As ICollection(Of Localidades) = New HashSet(Of Localidades)
    
    End Class

End Namespace
