'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class Proveedores
        Public Property IdProveedor As Integer
        Public Property Nombre As String
        Public Property RazonSocial As String
        Public Property Domicilio As String
        Public Property IdLocalidad As Integer
        Public Property Telefonos As String
        Public Property Fax As String
        Public Property Email As String
        Public Property Web As String
        Public Property Observaciones As String
        Public Property Cuit As String
        Public Property IIBB As String
        Public Property IdCondicionPago As Integer
        Public Property IdCondicionIva As Integer
        Public Property Bonificacion As Decimal
        Public Property Activo As Boolean
    
        Public Overridable Property Articulos As ICollection(Of Articulos) = New HashSet(Of Articulos)
        Public Overridable Property ComprobantesRemitosRecibidos As ICollection(Of ComprobantesRemitosRecibidos) = New HashSet(Of ComprobantesRemitosRecibidos)
        Public Overridable Property CondicionesIva As CondicionesIva
        Public Overridable Property CondicionesPago As CondicionesPago
        Public Overridable Property Localidades As Localidades
        Public Overridable Property ProveedoresNumerosCtasCtes As ICollection(Of ProveedoresNumerosCtasCtes) = New HashSet(Of ProveedoresNumerosCtasCtes)
    
    End Class

End Namespace
