'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class Rubros
        Public Property IdRubro As Integer
        Public Property Rubro As String
        Public Property Activo As Boolean
    
        Public Overridable Property SubRubros As ICollection(Of SubRubros) = New HashSet(Of SubRubros)
    
    End Class

End Namespace
