'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class Señas
        Public Property IdSeña As Integer
        Public Property IdComprobanteEmitido As Integer
        Public Property Pendiente As Boolean
    
        Public Overridable Property ComprobantesEmitidos As ComprobantesEmitidos
    
    End Class

End Namespace
