'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class SubRubros
        Public Property IdSubRubro As Integer
        Public Property IdRubro As Integer
        Public Property SubRubro As String
        Public Property Activo As Boolean
    
        Public Overridable Property Articulos As ICollection(Of Articulos) = New HashSet(Of Articulos)
        Public Overridable Property ArticulosOnline As ICollection(Of ArticulosOnline) = New HashSet(Of ArticulosOnline)
        Public Overridable Property Rubros As Rubros
    
    End Class

End Namespace
