'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class Talonarios
        Public Property IdTalonario As Integer
        Public Property Talonario As String
        Public Property Operacion As String
        Public Property Comprobante As String
        Public Property TipoComprobante As String
        Public Property CopiasComprobante As Integer
        Public Property ConIVA As Boolean
        Public Property DiscriminaIVA As Boolean
        Public Property PuntoVenta As Decimal
        Public Property PrimerNumeroHabilitado As Decimal
        Public Property UltimoNumeroHabilitado As Decimal
        Public Property ControladorFiscal As Boolean
        Public Property IdControladorFiscal As Integer
        Public Property PuertoControladorFiscal As Integer
        Public Property ComprobanteControladorFiscal As String
        Public Property Imprimir As Boolean
        Public Property Autonumerar As Boolean
        Public Property Impresora As String
        Public Property CantidadItems As Integer
        Public Property TalonarioPredeterminado As Boolean
        Public Property Activo As Boolean
    
        Public Overridable Property ControladoresFiscales As ControladoresFiscales
        Public Overridable Property TiposComprobantes As ICollection(Of TiposComprobantes) = New HashSet(Of TiposComprobantes)
    
    End Class

End Namespace
