'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class TasasIVACompras
        Public Property IdTasaIVACompras As Integer
        Public Property Tasa As Decimal
    
        Public Overridable Property Articulos As ICollection(Of Articulos) = New HashSet(Of Articulos)
    
    End Class

End Namespace
