'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class TiposComprobantes
        Public Property IdTipoComprobante As Integer
        Public Property IdCondicionIvaEmisor As Integer
        Public Property IdCondicionIvaReceptor As Integer
        Public Property IdTalonario As Nullable(Of Integer)
        Public Property TipoComprobante As String
        Public Property Activo As Boolean
    
        Public Overridable Property CondicionesIva As CondicionesIva
        Public Overridable Property CondicionesIva1 As CondicionesIva
        Public Overridable Property Talonarios As Talonarios
    
    End Class

End Namespace
