'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class TiposMovimientos
        Public Property IdTipoMovimiento As Integer
        Public Property Movimiento As String
        Public Property TipoMovimiento As String
        Public Property Activo As Boolean
    
        Public Overridable Property CajaMovimientos As ICollection(Of CajaMovimientos) = New HashSet(Of CajaMovimientos)
    
    End Class

End Namespace
