'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class UsuariosPerfiles
        Public Property IdUsuarioPerfil As Integer
        Public Property UsuarioPerfil As String
        Public Property Activo As Boolean
    
        Public Overridable Property Usuarios As ICollection(Of Usuarios) = New HashSet(Of Usuarios)
        Public Overridable Property UsuariosPerfilesConfiguracion As ICollection(Of UsuariosPerfilesConfiguracion) = New HashSet(Of UsuariosPerfilesConfiguracion)
    
    End Class

End Namespace
