'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Entidades

    Partial Public Class UsuariosPerfilesConfiguracion
        Public Property IdUsuarioPerfilConfiguracion As Integer
        Public Property IdUsuarioPerfil As Integer
        Public Property Orden As Integer
        Public Property Modulo As String
        Public Property Seccion As String
        Public Property NombreMenu As String
        Public Property Activo As Boolean
    
        Public Overridable Property UsuariosPerfiles As UsuariosPerfiles
    
    End Class

End Namespace
