'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports CapaEntidades.Entidades

Partial Public Class mdpGestionEMPRESAEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=mdpGestionEMPRESAEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property Articulos() As DbSet(Of Articulos)
    Public Property ArticulosCantidades() As DbSet(Of ArticulosCantidades)
    Public Property ArticulosImagenes() As DbSet(Of ArticulosImagenes)
    Public Property ArticulosOnline() As DbSet(Of ArticulosOnline)
    Public Property ArticulosOnlineDetalle() As DbSet(Of ArticulosOnlineDetalle)
    Public Property ArticulosPerfiles() As DbSet(Of ArticulosPerfiles)
    Public Property ArticulosPreciosCosto() As DbSet(Of ArticulosPreciosCosto)
    Public Property ArticulosPreciosVenta() As DbSet(Of ArticulosPreciosVenta)
    Public Property Bancos() As DbSet(Of Bancos)
    Public Property CajaCierres() As DbSet(Of CajaCierres)
    Public Property CajaMovimientos() As DbSet(Of CajaMovimientos)
    Public Property Clientes() As DbSet(Of Clientes)
    Public Property ClientesCtasCtes() As DbSet(Of ClientesCtasCtes)
    Public Property ClientesNumerosCtasCtes() As DbSet(Of ClientesNumerosCtasCtes)
    Public Property ComprobantesCobros() As DbSet(Of ComprobantesCobros)
    Public Property ComprobantesCobrosDetalle() As DbSet(Of ComprobantesCobrosDetalle)
    Public Property ComprobantesEmitidos() As DbSet(Of ComprobantesEmitidos)
    Public Property ComprobantesEmitidosDetalle() As DbSet(Of ComprobantesEmitidosDetalle)
    Public Property ComprobantesEmitidosVencimientos() As DbSet(Of ComprobantesEmitidosVencimientos)
    Public Property ComprobantesPagos() As DbSet(Of ComprobantesPagos)
    Public Property ComprobantesPagosDetalle() As DbSet(Of ComprobantesPagosDetalle)
    Public Property ComprobantesPedidosRecibidos() As DbSet(Of ComprobantesPedidosRecibidos)
    Public Property ComprobantesPedidosRecibidosDetalle() As DbSet(Of ComprobantesPedidosRecibidosDetalle)
    Public Property ComprobantesPresupuestosEmitidos() As DbSet(Of ComprobantesPresupuestosEmitidos)
    Public Property ComprobantesPresupuestosEmitidosDetalle() As DbSet(Of ComprobantesPresupuestosEmitidosDetalle)
    Public Property ComprobantesRecibidos() As DbSet(Of ComprobantesRecibidos)
    Public Property ComprobantesRecibidosDetalle() As DbSet(Of ComprobantesRecibidosDetalle)
    Public Property ComprobantesRecibidosVencimientos() As DbSet(Of ComprobantesRecibidosVencimientos)
    Public Property ComprobantesRemitosEmitidos() As DbSet(Of ComprobantesRemitosEmitidos)
    Public Property ComprobantesRemitosEmitidosDetalle() As DbSet(Of ComprobantesRemitosEmitidosDetalle)
    Public Property ComprobantesRemitosRecibidos() As DbSet(Of ComprobantesRemitosRecibidos)
    Public Property ComprobantesRemitosRecibidosDetalle() As DbSet(Of ComprobantesRemitosRecibidosDetalle)
    Public Property CondicionesIva() As DbSet(Of CondicionesIva)
    Public Property CondicionesPago() As DbSet(Of CondicionesPago)
    Public Property ConfiguracionFactura() As DbSet(Of ConfiguracionFactura)
    Public Property ConfiguracionNotaCredito() As DbSet(Of ConfiguracionNotaCredito)
    Public Property ConfiguracionOrdenPago() As DbSet(Of ConfiguracionOrdenPago)
    Public Property ConfiguracionPedido() As DbSet(Of ConfiguracionPedido)
    Public Property ConfiguracionPresupuesto() As DbSet(Of ConfiguracionPresupuesto)
    Public Property ConfiguracionRecibo() As DbSet(Of ConfiguracionRecibo)
    Public Property ConfiguracionRemito() As DbSet(Of ConfiguracionRemito)
    Public Property ControladoresFiscales() As DbSet(Of ControladoresFiscales)
    Public Property ControladoresFiscalesComprobantes() As DbSet(Of ControladoresFiscalesComprobantes)
    Public Property Depositos() As DbSet(Of Depositos)
    Public Property DetalleChequesEmitidos() As DbSet(Of DetalleChequesEmitidos)
    Public Property DetalleChequesRecibidos() As DbSet(Of DetalleChequesRecibidos)
    Public Property DetalleCobrosBancos() As DbSet(Of DetalleCobrosBancos)
    Public Property DetalleCobrosTarjetas() As DbSet(Of DetalleCobrosTarjetas)
    Public Property DetallePagosBancos() As DbSet(Of DetallePagosBancos)
    Public Property Empresa() As DbSet(Of Empresa)
    Public Property Escalas1() As DbSet(Of Escalas1)
    Public Property Escalas2() As DbSet(Of Escalas2)
    Public Property FormasPago() As DbSet(Of FormasPago)
    Public Property Localidades() As DbSet(Of Localidades)
    Public Property Proveedores() As DbSet(Of Proveedores)
    Public Property ProveedoresCtasCtes() As DbSet(Of ProveedoresCtasCtes)
    Public Property ProveedoresNumerosCtasCtes() As DbSet(Of ProveedoresNumerosCtasCtes)
    Public Property Provincias() As DbSet(Of Provincias)
    Public Property Rubros() As DbSet(Of Rubros)
    Public Property Señas() As DbSet(Of Señas)
    Public Property SubRubros() As DbSet(Of SubRubros)
    Public Property Talonarios() As DbSet(Of Talonarios)
    Public Property TasasIVACompras() As DbSet(Of TasasIVACompras)
    Public Property TasasIVAVentas() As DbSet(Of TasasIVAVentas)
    Public Property TiposComprobantes() As DbSet(Of TiposComprobantes)
    Public Property TiposMovimientos() As DbSet(Of TiposMovimientos)
    Public Property Transportes() As DbSet(Of Transportes)
    Public Property Usuarios() As DbSet(Of Usuarios)
    Public Property UsuariosPerfiles() As DbSet(Of UsuariosPerfiles)
    Public Property UsuariosPerfilesConfiguracion() As DbSet(Of UsuariosPerfilesConfiguracion)
    Public Property Vendedores() As DbSet(Of Vendedores)

End Class
